// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXBKIZvXd0DiqyjEVnTASKtXZUjTDXBo',
    appId: '1:823634732427:web:bb0a91cfa97e7801e27b8e',
    messagingSenderId: '823634732427',
    projectId: 'crudapp-2e8ef',
    authDomain: 'crudapp-2e8ef.firebaseapp.com',
    storageBucket: 'crudapp-2e8ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7kuF9Le5A64W4GYmyL53Fz97ePWHqKw',
    appId: '1:823634732427:android:440e4a66b9dd9afae27b8e',
    messagingSenderId: '823634732427',
    projectId: 'crudapp-2e8ef',
    storageBucket: 'crudapp-2e8ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz5Pq9NtArRsLsDygXMrZNwybBJfLzvVs',
    appId: '1:823634732427:ios:2777a1197eedc0a9e27b8e',
    messagingSenderId: '823634732427',
    projectId: 'crudapp-2e8ef',
    storageBucket: 'crudapp-2e8ef.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz5Pq9NtArRsLsDygXMrZNwybBJfLzvVs',
    appId: '1:823634732427:ios:2777a1197eedc0a9e27b8e',
    messagingSenderId: '823634732427',
    projectId: 'crudapp-2e8ef',
    storageBucket: 'crudapp-2e8ef.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgXBKIZvXd0DiqyjEVnTASKtXZUjTDXBo',
    appId: '1:823634732427:web:be2fb8921298599be27b8e',
    messagingSenderId: '823634732427',
    projectId: 'crudapp-2e8ef',
    authDomain: 'crudapp-2e8ef.firebaseapp.com',
    storageBucket: 'crudapp-2e8ef.appspot.com',
  );
}
